function getDeck() {
  return { black: black(), white: white() };
}

function black() {
  return [
  	"I denne uges Hvad er det værd vil vi lægge ud med at se på __________.",
  	"Vielsesceremonien endte brat, da __________ pludselig dukkede op.",
  	"Som din advokat vill jeg råde dig til ikke at nævne __________ under afhøringen",
  	"De danske soldater i Afghanistan vandt lokalbefolkningens tillid ved at medbringe __________",
  	"Til salg: __________, kun brugt få gange, 350 KR",
  	"Jordmoderen fik sig et chock, da hun under fødslen hev __________ ud af den målløse mor.",
  	"Det eneste, jeg kan huske fra i går, er __________",
  	"En rumæner blev her til aften anholdt på Strøget for at sælge __________.",
  	"Hashrygning kan medføre __________",
  	"Vi vidste, at farmor var blevet senil, da hun medbragte __________ til familiefesten",
  	"De unge mødre, afsnit 302 '__________'",
  	"Københavns politi forsøger sig nu med civilbetjente forklædt som __________",
  	"Jeg har et rum i kælderen kun til __________",
  	"Når jeg rigtig skal tænde min kæreste, klæder jeg mig ud som __________.",
    "Jeg har lige købt __________",
    "Luftfartsmyndighederne forbyder nu __________ på rutefly",
    "Det en skam at unge nu til dags alle bliver involverede i __________",
    "Næste gang i 'De unge mødre': Hvordan taler du med dit barn om__________",
    "Højt fra træets grønne top, stråler __________",
    "Der er kun to ting i livet man kan være sikker på: død og __________",
    "Dansk Boldspils Union har forbudt __________, da det giver en unfair fordel",
    "Hvad har jeg postet på Instagram?",
    "Hvad er det eneste, der forhindrer mig i at tage narko?",
    "Vejen til succes kræver __________",
    "Tale er sølv, __________ er guld.",
    "Hvad er den nyeste slankekur?",
    "Hvad er temaet i den næste 'Spise med Price'?",
    "I denne uges M! blad 'Sæt fut i dit sexliv ved hjælp af __________",
    "Jeg dyrker fitness, for at jeg kan se godt ud, når jeg er i gang med __________",
    "Hvordan holder jeg mit forhold ved lige",
    "Den bedste julegave, jeg fik fra mormor, var __________",
    "Helle Thorning ønsker mere __________ i Danmark",
    "Hvis alt andet kikser, kan jeg altid onanere til __________",
    "I 7. klasse elskede jeg at onanere til __________",
    "Walid Knaldperlen plejede tit at sige, at han elskede __________",
    "Studieturen blev fuldstændig ødelagt af __________",
    "Hvad er en piges bedste ven?",
    "Når jeg bliver statsminister, vil jeg oprette Ministeriet for",
    "I gymnasiet passede jeg ikke rigtig ind, indtil jeg fandt sammen med andre der også gik op i __________",
    "Hvad siger du til at tage hjem til mig og se min",
    "Når jeg har sex, fantaserer jeg tit om __________",
    "Horsens HF & VUC er lige begyndt at undervise i __________",
    "Hvad bruger Helle Thorning til at slappe af?",
    "Jeg skider altid i bukserne, når jeg ser",
    "Hvad foretrækker Lars Løkke Rasmussen?",
    "Jeg drikker for at glemme __________",
    "Min hunds ånde minder mig om __________",
    "I badet kan jeg finde på at __________",
    "Kanal 4 præsenterer __________",
    "Min favouritplakat var et billede af __________",
    "Gæt og grimasser blev permanent ødelagt, da mor skulle vise __________",
    "Jesus er __________.",
    "Det næste afsnit af Kongerne handler om __________",
    "Min mor blev chockeret, da hun så min browserhistorik og fandt __________.com",
    "Medinas nye single handler om __________",
    "Rasmus Seebach har i TV fortalt om hans svaghed for __________",
    "Når jeg er alene lukker jeg døren til min værelse og ser på __________",
    "Mit liv fik sit vendepunkt, da __________ kom ind i mit liv",
    "Jehovas Vidner bankede på min dør og snakkede om __________",
    "Helle Thorning blev for leden taget i at __________",
    "Den nye iPhone giver dig nu mulighed for at __________ uden problemer",
    "Efter at have fistet min kæreste popppede en __________ ud",
    "Er svaret på alt",
    "Hvordan fikser du et knust hjerte?",
    "Fie Laursens nye sang __________ har fået massere af succes",
    "Det siges at Fie Laursens nye kæreste er __________",
    "Fie Laursen blev forleden taget i at kysse med __________",
    "Burhan G er forleden set sammen med en __________",
    "Burhan G er efter 10 års flirteri endelig kommet sammen med __________",
    "Burhan G's nye single __________ er kommet i top 10 over mest forfærdelige sange",
    "For tiden har jeg drømt rigtig meget om __________",
    "Det eneste, jeg husker fra gymnasiefesten, var __________",
    "Nu på DR1: __________",
    "Er sådan jeg vil dø",
    "Hvad ødelagde mit sidste forhold?",
    "Imens jeg har sex kan jeg lide at tænke på __________",
    "Jeg har 99 problemer, men __________ er ikke en",
    "Hvem bliver den næste statsminister?",
    "Nobelprisen går til __________",
    "Mauran blev forarget da han så Jesus give __________",
    "Når jeg er ensom kan jeg godt lide at tænde for mit tv og se __________",
    "__________ har smittet mig med AIDS",
    "Min mor postede forleden at billede af __________ på Facebook",
    "Jeg er lige blevet venner med __________ på Facebook",
    "I dag bankede __________ på min dør",
    "Jeg havde hed sex med __________ i nat",
    "Jeg har lige købt __________ for 500 kr i Thailand!",
    "Min mor har lige set __________ blive ammet",
    "Min mor kiggede på min fars nye __________",
    "Om natten har jeg sex med __________",
    "I næste episode af Hammerslag: __________",
    "Jeg har altid fået at vide at jeg minder om __________",
    "I TV2 fortalte __________ om hans pik",
    "Grunden til at alle forhold slutter",
    "Jeg mødte __________ i Fakta!",
    "Børn i Afrika er en dansk forening som arbejder for __________ børn i Afrika, foreningen har 1000 medlemmer.",
    "Menneskets hjerte har millarder af __________"
  ];
}

function white() {
  return [
   "At skide i pissoriet",
   "Ole Wedel",
   "At blive ammet",
   "18 millioner mennesker",
   "En totalskadet toyota",
   "Den næsten ligeså dygtige kirug",
   "Skumfest",
   "Thor og Odin på ecstasy",
   "At vinde i russisk roulette",
   "Hårde fyre fra ballerup",
   "civilbetjente",
   "Kønsskifteoperation nr. 2",
   "En af mine gode venner",
   "Druk med terpetin",
   "Et røgfyldt lokale",
   "Endnu et polititilhold",
   "En sjusket intimbarbering",
   "Knivstik",
   "Et slapt håndtryk",
   "Sussi og leo der dyrker oralsex i slowmotion",
   "En bemærkelsesværdi grim frisure",
   "Forhudsbetændelse",
   "En tattovering på lænden",
   "Et uangeret blowjob",
   "En ubelejelig stådreng",
   "At få blod på hænderne",
   "Bedøvet ofre",
   "Mænd, der råber",
   "En flæskesteg med sprøde svær",
   "En million kroner i sportstaske",
   "At nægte ejerskab til sin prut",
   "TALEBAN KRIGERE",
   "At tisse lidt i sengen",
   "Grøn koncert",
   "Runde tårn",
   "Dyr, som ikke vil dø",
   "To timers tysk dominansporno",
   "En alt for fed fest",
   "En utilstrækkelig narkose",
   "En hoppeborg fyldt med muskelhunde",
   "En tyranusaurus rex",
   "Afklippede tånegle",
   "500 KG krydsfiner",
   "Crocs-sandaler",
   "Flager af tør hud",
   "Et ladt haglgevær",
   "Et kul hundehvalpe",
   "En sulten hæmoride",
   "Et superfedt bælte",
   "Fedtede fingre",
   "Store mængder tun i Olie",
   "At give finger",
   "At lurer",
   "100% rent saft",
   "Big fat snakes samlede værker",
   "At bo hjemme hos mor",
   "Tyndskid",
   "En flok vilde ulve",
   "Puk elgaard",
   "Kogt vand",
   "Nogle alt for stærke joints",
   "Et dameoverskæg",
   "En tyrkisk buffet",
   "Et tusind skarptslebne sakse",
   "To pizza hawaii",
   "Natfærgen til polen",
   "Et glas fun",
   "Hele lortet",
   "En fejlamputering",
   "Lidt for meget pølse",
   "Min frækkeste fantasi",
   "Tre ugers fængsel",
   "God dansk hygge",
   "Tvangsfodring",
   "En på alle måder uværdig oplevelse",
   "En tung kvalme",
   "Fri hash",
   "Politibrutalitet",
   "Fællesbadning",
   "En hemmelig identitet",
   "Det sidste skamfulde stød før klimaks",
   "Dumsmarte bemærkninger",
   "Satan",
   "En nettopose fyldt med øl",
   "Samleje",
   "Walid Knaldperlen",
   "Helle Thorning",
   "En fadøl",
   "Menstruationsblod",
   "Rigtig svensk mad",
   "Pornostjerner",
   "Jylland",
   "Børn med kræft i røven",
   "Pandasex",
   "Nøgenhed",
   "Kaskelothvaler",
   "Hjemløse",
   "Store nørd",
   "Kongerne af Svendborg",
   "Incest",
   "Sort mennesker",
   "Bubber",
   "John Hitler",
   "At lægge et æg",
   "Følelser",
   "Carlsberg Pilsner",
   "Moderkage",
   "Bollevenner",
   "Et afbleget røvhul",
   "Champagne",
   "Onani",
   "En fræk mongol",
   "Spiseligt undertøj",
   "Bang og snavset er væk!",
   "Anders Mattesen",
   "Kanye West",
   "Pikbefængte fingre",
   "Nakkeost",
   "Pædofile",
   "Analperler",
   "Fattige folk",
   "Telefonsex",
   "Tysk analsex",
   "At tørre hende bagi",
   "At gøre det i røven",
   "Slappe skamlæber",
   "AIDS",
   "Billeder af bryster",
   "En stiv diller der holder mere end 4 timer",
   "Mine kønsorganer",
   "Honey Monster",
   "At samle piger op på abortklinikken",
   "Misundelse af penis",
   "Fugl der ikke kan flyve",
   "KKK",
   "Døde babyer",
   "Forhud",
   "Børnelokkere",
   "Amalies skuespilskarrier",
   "Et foster",
   "At tisse lidt",
   "Bulimi",
   "Stærke lår.",
   "Racisme",
   "Mit forhold på Facebook",
   "At smile frækt til ældre mennesker",
   "En abe der ryger en cigar",
   "Harry Potter porno",
   "Gymnasiet",
   "Geo's manglende testikel",
   "Walid knaldperlen som 50-årig",
   "Folkeskolen",
   "Facebook",
   "At vågne halvnøgen på parkeringspladsen udenfor Jensens Bøfhus",
   "Ghita nørbys vagina",
   "Sidney Lee der bliver jagtet af en flok gribbe",
   "Min kusse",
   "Brystmælk",
   "Justin Bieber",
   "Pubertet",
   "Min samling af sexlegetøj",
   "Hvide mennesker",
   "En mikropenis",
   "En klam frokostpizza",
   "Tentakelporno",
   "Min sjæl",
   "Politivold",
   "Christiania",
   "Lækre mennesker",
   "At forfører",
   "Gæs",
   "En skede der fører ind i en anden dimension",
   "Homo-rumvæsner",
   "Kvinders stemmeret",
   "En godt brugt lolitadukke sælges brugt på DBA.dk",
   "Arto",
   "Et ødelagt kondom",
   "At få sit lem til at sidde fast i en kinesisk fingerfæld, med en andens lem i den modsatte ende.",
   "Barack Obama",
   "Rødhårede",
   "Et blowjob i bilen",
   "Pebernødder",
   "Et billede af en mand der spreder hans baller",
   "At blive bøsse for at scorer Ryan Gosling",
   "Analvorter",
   "Mit sexliv",
   "Hannah Montana",
   "Klitoris",
   "At stikke pikken ind i en tærte",
   "At tweete det",
   "Ville Søvndals dårlige engelsk",
   "Mig tid",
   "En hjemmevideo af Amin Jensen der græder ned i sin salat",
   "At være fantastisk til sex",
   "At kramme bedstemor imens du har en stådreng",
   "Patter der hænger helt ned til knæene",
   "Søren Pind",
   "Simon Emil Amitzbøl",
   "Masturber",
   "Kneppe heste",
   "Lave en hestelasagne",
   "Jeppe K",
   "Det lig' meget!",
   "Deltage i MGP",
   "Deltager i X-factor",
   "Haft sex med Basim",
   "Ole Wedel",
   "Deltage i Mig og min mor",
   "Deltage i Paradise hotel",
   "Haft hed sex med en skildpadde",
   "Givet Michael Jackson et blowjob",
   "Sutte sin egen pik",
   "Menstruere ned i en kop",
   "Have sex med en Pia Kjærsgaard",
   "Dansk Folkeparti",
   "Pia Kjærsgaard",
   "Lebbesex",
   "Gustav",
   "Skedejuice",
   "Blowjob fra bedstemor",
   "Slap fisse",
   "En alf",
   "Mauran",
   "Helle Thornings brugte trusser",
   "Afbrændt forhud",
   "En transseksuel",
   "Ryan Gosling",
   "Orgiesex",
   "Det en hugorm!",
   "Min pik er hoar",
   "Walids penis",
   "Rejeost",
   "En blendet kage",
   "Mor Jette",
   "Amalie fra Paradise",
   "Nirvanas ældste fisse",
   "Club Zensyg",
   "En fyr der kalder sig selv MAGIC",
   "Ibo",
   "Casp",
   "Jeg sortere müsli",
   "Jeg ville bare gerne lige prøve... Hvordan det VAR",
   "Nu jeg jo blevet pædofil",
   "Kan du så forstå det, Marianne!",
   "De parre sig om natten",
   "Vi spiller om guld og tis!",
   "Rene Dif er bare så supersød!",
   "Humor? Nej tak! Brintbome JA TAK",
   "Årh min stakkels targmregion",
   "Anders Lund Madsen er en menneskelig stavefejl",
   "Helt stille som en Ninja!",
   "ARGHHHH",
   "Can i fuck your tiny ass?",
   "You have very sexy ears!",
   "Klistret bæverjuice",
   "En lille pige fra afrika der lige har fået sin første menstruation",
   "Man kan vel købe et par sko for de penge",
   "Min mors menstruationsblod",
   "En død fugl",
   "En musikvideo af Walid Knaldperlen der knepper Simon Emil Amitzbøl"
  ];
}

exports.getDeck = getDeck;
